import glob
import os
import sys
import shutil
import pandas as pd
from pyulog import ULog

# Valid categories matching the folder structure
VALID_CATEGORIES = ["nominal", "step_attack", "ramp_attack", "stealth_attack"]

def get_next_flight_number(base_dir):
    """Finds the next sequential flight number (e.g., flight_01, flight_02) in a directory."""
    os.makedirs(base_dir, exist_ok=True)
    existing_dirs = [d for d in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, d)) and d.startswith("flight_")]
    if not existing_dirs:
        return "flight_01"
    
    # Extract numbers, find max, increment
    nums = [int(d.split('_')[1]) for d in existing_dirs if d.split('_')[1].isdigit()]
    next_num = max(nums) + 1 if nums else 1
    return f"flight_{next_num:02d}"

def extract_and_organize():
    if len(sys.argv) != 2 or sys.argv[1] not in VALID_CATEGORIES:
        print(f"Usage: python3 src/pipeline/01_extract_logs.py <category>")
        print(f"Valid categories: {', '.join(VALID_CATEGORIES)}")
        sys.exit(1)

    category = sys.argv[1]

    # 1. Resolve the latest ULog file generated by PX4
    log_dir = os.path.expanduser("~/PX4-Autopilot/build/px4_sitl_default/rootfs/fs/log")
    try:
        latest_log = max(glob.glob(f"{log_dir}/**/*.ulg", recursive=True), key=os.path.getctime)
    except ValueError:
        print(f"[!] No .ulg files found in {log_dir}")
        sys.exit(1)

    print(f"[*] Found newest ULog: {latest_log}")

    # 2. Determine project paths
    project_root = "/home/ualr/Documents/Drone_GPS_Simulation"
    raw_category_dir = os.path.join(project_root, "data", "raw_ulog", category)
    processed_category_dir = os.path.join(project_root, "data", "processed", category)

    flight_id = get_next_flight_number(processed_category_dir)
    
    # Setup final destination paths
    raw_dest = os.path.join(raw_category_dir, f"{flight_id}.ulg")
    processed_dest = os.path.join(processed_category_dir, flight_id)
    
    os.makedirs(raw_category_dir, exist_ok=True)
    os.makedirs(processed_dest, exist_ok=True)

    # 3. Archive the raw log
    print(f"[*] Archiving raw log to: {raw_dest}")
    shutil.copy2(latest_log, raw_dest)

    # 4. Extract telemetry
    print(f"[*] Extracting telemetry to: {processed_dest}...")
    ulog = ULog(raw_dest)

    def get_data(topic):
        try:
            return ulog.get_dataset(topic).data
        except Exception:
            return None

    ekf_est = get_data('vehicle_local_position')
    ekf_true = get_data('vehicle_local_position_groundtruth')
    innov = get_data('estimator_innovations')
    ratios = get_data('estimator_innovation_test_ratios')
    gnss = get_data('sensor_gnss')
    imu = get_data('sensor_combined')

    # Export Estimated Local Position
    if ekf_est is not None:
        pd.DataFrame({
            'timestamp': ekf_est['timestamp'],
            'x': ekf_est['x'], 'y': ekf_est['y'], 'z': ekf_est['z'],
            'vx': ekf_est['vx'], 'vy': ekf_est['vy'], 'vz': ekf_est['vz']
        }).to_csv(os.path.join(processed_dest, "ekf_estimated.csv"), index=False)

    # Export Ground Truth Position
    if ekf_true is not None:
        pd.DataFrame({
            'timestamp': ekf_true['timestamp'],
            'x_true': ekf_true['x'], 'y_true': ekf_true['y'], 'z_true': ekf_true['z'],
            'vx_true': ekf_true['vx'], 'vy_true': ekf_true['vy'], 'vz_true': ekf_true['vz']
        }).to_csv(os.path.join(processed_dest, "ground_truth.csv"), index=False)

    # Export EKF Innovations & Test Ratios
    if innov is not None and ratios is not None:
        pd.DataFrame({
            'timestamp': innov['timestamp'],
            'vel_innov_n': innov.get('gps_vvel[0]', innov.get('vel_innov[0]', 0)),
            'vel_innov_e': innov.get('gps_vvel[1]', innov.get('vel_innov[1]', 0)),
            'pos_innov_n': innov.get('gps_hpos[0]', innov.get('pos_innov[0]', 0)),
            'pos_innov_e': innov.get('gps_hpos[1]', innov.get('pos_innov[1]', 0)),
            'test_ratio_vel': ratios.get('gps_vel', ratios.get('vel_test_ratio', 0)),
            'test_ratio_pos': ratios.get('gps_hpos', ratios.get('pos_test_ratio', 0))
        }).to_csv(os.path.join(processed_dest, "ekf_innovations.csv"), index=False)
        
    # Export IMU
    if imu is not None:
        pd.DataFrame({
            'timestamp': imu['timestamp'],
            'accel_x': imu['accelerometer_m_s2[0]'],
            'accel_y': imu['accelerometer_m_s2[1]'],
            'accel_z': imu['accelerometer_m_s2[2]'],
            'gyro_x': imu['gyro_rad[0]'],
            'gyro_y': imu['gyro_rad[1]'],
            'gyro_z': imu['gyro_rad[2]']
        }).to_csv(os.path.join(processed_dest, "imu.csv"), index=False)
        
    # Export GNSS
    if gnss is not None:
        pd.DataFrame({
            'timestamp': gnss['timestamp'],
            # PX4 logs lat/lon as int32 scaled by 1e7
            'lat': gnss.get('lat', gnss['timestamp']*0) / 1e7,
            'lon': gnss.get('lon', gnss['timestamp']*0) / 1e7,
            # Altitude is in millimeters, convert to meters
            'alt': gnss.get('alt', gnss['timestamp']*0) / 1e3,
            'vel_n': gnss.get('vel_n_m_s', 0),
            'vel_e': gnss.get('vel_e_m_s', 0),
            'vel_d': gnss.get('vel_d_m_s', 0)
        }).to_csv(os.path.join(processed_dest, "gnss.csv"), index=False)
    else:
        print("[-] Warning: 'vehicle_gps_position' not found in log.")

    print(f"[+] Done. Flight {flight_id} processed successfully.")

if __name__ == "__main__":
    extract_and_organize()